options:
    snap-channel:
        type: string
        description: 'The channel to use to install the gitea snap.'
        default: 'latest/edge'
    example_int_config:
        type: int
        description: 'An example integer configuration item'
        default: 9001
    example_boolean_config:
        type: boolean
        description: 'An example boolean configuration item'
        default: false
